name = "pokemon-game-api"
main = "dist/index.js"
compatibility_date = "2024-04-29"

[build]
command = "npm run build"
watch_dir = "src"

# 開発環境の設定
[dev]
port = 8787
local_protocol = "http"
host = "127.0.0.1"

# [vars]
# MY_VARIABLE = "production_value"

[kv_namespaces]
# 開発環境用のローカルKV名前空間
[[kv_namespaces]]
binding = "GAME_STORE"
id = "dev-game-store"
preview_id = "dev-game-store"

[[d1_databases]]
binding = "DB"
database_name = "pokelike"
database_id = "c63d6cf7-90af-440b-9b16-937eb34c0195"

[triggers]
crons = [ ]

# [env.staging]
# name = "pokemon-game-api-staging"
# workers_dev = true
