name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Verify package-lock.json is in sync
      run: |
        # Check if package-lock is in sync
        npm install --package-lock-only
        git diff --exit-code package-lock.json || (echo "package-lock.json is not in sync with package.json. Run 'npm install' to update it." && exit 1)
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm run test
